# Generated by Django 2.1.7 on 2019-02-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_grande', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
            ],
        ),
    ]
